fix: incorrect PanelMenu import
SyntaxError: The requested module 'resource:///org/gnome/shell/ui/panelMenu.js' doesn't provide an export named: 'default' @ file:///home/ahann/.local/share/gnome-shell/extensions/pop-shell@system76.com/panel_settings.js:4:8